import {useState} from "react";
import {useRouter} from "next/navigation";
import * as yup from "yup";

export const stateAndLGA = {
    Abia: [
        "Aba North",
        "Aba South",
        "Arochukwu",
        "Bende",
        "Ikwuano",
        "Isiala-Ngwa North",
        "Isiala-Ngwa South",
        "Isuikwato",
        "Obi Nwa",
        "Ohafia",
        "Osisioma",
        "Ngwa",
        "Ugwunagbo",
        "Ukwa East",
        "Ukwa West",
        "Umuahia North",
        "Umuahia South",
        "Umu-Neochi"
    ],
    Adamawa: [
        "Demsa",
        "Fufore",
        "Ganaye",
        "Gireri",
        "Gombi",
        "Guyuk",
        "Hong",
        "Jada",
        "Lamurde",
        "Madagali",
        "Maiha",
        "Mayo-Belwa",
        "Michika",
        "Mubi North",
        "Mubi South",
        "Numan",
        "Shelleng",
        "Song",
        "Toungo",
        "Yola North",
        "Yola South"
    ],
    Anambra: [
        "Aguata",
        "Anambra East",
        "Anambra West",
        "Anaocha",
        "Awka North",
        "Awka South",
        "Ayamelum",
        "Dunukofia",
        "Ekwusigo",
        "Idemili North",
        "Idemili south",
        "Ihiala",
        "Njikoka",
        "Nnewi North",
        "Nnewi South",
        "Ogbaru",
        "Onitsha North",
        "Onitsha South",
        "Orumba North",
        "Orumba South",
        "Oyi"
    ],
    "Akwa-Ibom": [
        "Abak",
        "Eastern Obolo",
        "Eket",
        "Esit Eket",
        "Essien Udim",
        "Etim Ekpo",
        "Etinan",
        "Ibeno",
        "Ibesikpo Asutan",
        "Ibiono Ibom",
        "Ika",
        "Ikono",
        "Ikot Abasi",
        "Ikot Ekpene",
        "Ini",
        "Itu",
        "Mbo",
        "Mkpat Enin",
        "Nsit Atai",
        "Nsit Ibom",
        "Nsit Ubium",
        "Obot Akara",
        "Okobo",
        "Onna",
        "Oron",
        "Oruk Anam",
        "Udung Uko",
        "Ukanafun",
        "Uruan",
        "Urue-Offong/Oruko ",
        "Uyo"
    ],
    Bauchi: [
        "Alkaleri",
        "Bauchi",
        "Bogoro",
        "Damban",
        "Darazo",
        "Dass",
        "Ganjuwa",
        "Giade",
        "Itas/Gadau",
        "Jama'are",
        "Katagum",
        "Kirfi",
        "Misau",
        "Ningi",
        "Shira",
        "Tafawa-Balewa",
        "Toro",
        "Warji",
        "Zaki"
    ],
    Bayelsa: [
        "Brass",
        "Ekeremor",
        "Kolokuma/Opokuma",
        "Nembe",
        "Ogbia",
        "Sagbama",
        "Southern Jaw",
        "Yenegoa"
    ],
    Benue: [
        "Ado",
        "Agatu",
        "Apa",
        "Buruku",
        "Gboko",
        "Guma",
        "Gwer East",
        "Gwer West",
        "Katsina-Ala",
        "Konshisha",
        "Kwande",
        "Logo",
        "Makurdi",
        "Obi",
        "Ogbadibo",
        "Oju",
        "Okpokwu",
        "Ohimini",
        "Oturkpo",
        "Tarka",
        "Ukum",
        "Ushongo",
        "Vandeikya"
    ],
    Borno: [
        "Abadam",
        "Askira/Uba",
        "Bama",
        "Bayo",
        "Biu",
        "Chibok",
        "Damboa",
        "Dikwa",
        "Gubio",
        "Guzamala",
        "Gwoza",
        "Hawul",
        "Jere",
        "Kaga",
        "Kala/Balge",
        "Konduga",
        "Kukawa",
        "Kwaya Kusar",
        "Mafa",
        "Magumeri",
        "Maiduguri",
        "Marte",
        "Mobbar",
        "Monguno",
        "Ngala",
        "Nganzai",
        "Shani"
    ],
    "Cross-River": [
        "Akpabuyo",
        "Odukpani",
        "Akamkpa",
        "Biase",
        "Abi",
        "Ikom",
        "Yarkur",
        "Odubra",
        "Boki",
        "Ogoja",
        "Yala",
        "Obanliku",
        "Obudu",
        "Calabar South",
        "Etung",
        "Bekwara",
        "Bakassi",
        "Calabar Municipality"
    ],
    Delta: [
        "Oshimili",
        "Aniocha",
        "Aniocha South",
        "Ika South",
        "Ika North-East",
        "Ndokwa West",
        "Ndokwa East",
        "Isoko south",
        "Isoko North",
        "Bomadi",
        "Burutu",
        "Ughelli South",
        "Ughelli North",
        "Ethiope West",
        "Ethiope East",
        "Sapele",
        "Okpe",
        "Warri North",
        "Warri South",
        "Uvwie",
        "Udu",
        "Warri Central",
        "Ukwani",
        "Oshimili North",
        "Patani"
    ],
    Ebonyi: [
        "Edda",
        "Afikpo",
        "Onicha",
        "Ohaozara",
        "Abakaliki",
        "Ishielu",
        "lkwo",
        "Ezza",
        "Ezza South",
        "Ohaukwu",
        "Ebonyi",
        "Ivo"
    ],
    Enugu: [
        "Enugu South,",
        "Igbo-Eze South",
        "Enugu North",
        "Nkanu",
        "Udi Agwu",
        "Oji-River",
        "Ezeagu",
        "IgboEze North",
        "Isi-Uzo",
        "Nsukka",
        "Igbo-Ekiti",
        "Uzo-Uwani",
        "Enugu Eas",
        "Aninri",
        "Nkanu East",
        "Udenu."
    ],
    Edo: [
        "Esan North-East",
        "Esan Central",
        "Esan West",
        "Egor",
        "Ukpoba",
        "Central",
        "Etsako Central",
        "Igueben",
        "Oredo",
        "Ovia SouthWest",
        "Ovia South-East",
        "Orhionwon",
        "Uhunmwonde",
        "Etsako East",
        "Esan South-East"
    ],
    Ekiti: [
        "Ado",
        "Ekiti-East",
        "Ekiti-West",
        "Emure/Ise/Orun",
        "Ekiti South-West",
        "Ikere",
        "Irepodun",
        "Ijero,",
        "Ido/Osi",
        "Oye",
        "Ikole",
        "Moba",
        "Gbonyin",
        "Efon",
        "Ise/Orun",
        "Ilejemeje."
    ],
    FCT: [
        "Abaji",
        "Abuja Municipal",
        "Bwari",
        "Gwagwalada",
        "Kuje",
        "Kwali"
    ],
    Gombe: [
        "Akko",
        "Balanga",
        "Billiri",
        'Dukku',
        "Kaltungo",
        "Kwami",
        "Shomgom",
        "Funakaye",
        "Gombe",
        "Nafada/Bajoga",
        "Yamaltu/Delta."
    ],
    Imo: [
        "Aboh-Mbaise",
        "Ahiazu-Mbaise",
        "Ehime-Mbano",
        "Ezinihitte",
        "Ideato North",
        "Ideato South",
        "Ihitte/Uboma",
        "Ikeduru",
        "Isiala Mbano",
        "Isu",
        "Mbaitoli",
        "Mbaitoli",
        "Ngor-Okpala",
        "Njaba",
        "Nwangele",
        "Nkwerre",
        "Obowo",
        "Oguta",
        "Ohaji/Egbema",
        "Okigwe",
        "Orlu",
        "Orsu",
        "Oru East",
        "Oru West",
        "Owerri-Municipal",
        "Owerri North",
        "Owerri West"
    ],
    Jigawa: [
        "Auyo",
        "Babura",
        "Birni Kudu",
        "Biriniwa",
        "Buji",
        "Dutse",
        "Gagarawa",
        "Garki",
        "Gumel",
        "Guri",
        "Gwaram",
        "Gwiwa",
        "Hadejia",
        "Jahun",
        "Kafin Hausa",
        "Kaugama Kazaure",
        "Kiri Kasamma",
        "Kiyawa",
        "Maigatari",
        "Malam Madori",
        "Miga",
        "Ringim",
        "Roni",
        "Sule-Tankarkar",
        "Taura",
        "Yankwashi"
    ],
    Kaduna: [
        "Birni-Gwari",
        "Chikun",
        "Giwa",
        "Igabi",
        "Ikara",
        "jaba",
        "Jema'a",
        "Kachia",
        "Kaduna North",
        "Kaduna South",
        "Kagarko",
        "Kajuru",
        "Kaura",
        "Kauru",
        "Kubau",
        "Kudan",
        "Lere",
        "Makarfi",
        "Sabon-Gari",
        "Sanga",
        "Soba",
        "Zango-Kataf",
        "Zaria"
    ],
    Kano: [
        "Ajingi",
        "Albasu",
        "Bagwai",
        "Bebeji",
        "Bichi",
        "Bunkure",
        "Dala",
        "Dambatta",
        "Dawakin Kudu",
        "Dawakin Tofa",
        "Doguwa",
        "Fagge",
        "Gabasawa",
        "Garko",
        "Garum",
        "Mallam",
        "Gaya",
        "Gezawa",
        "Gwale",
        "Gwarzo",
        "Kabo",
        "Kano Municipal",
        "Karaye",
        "Kibiya",
        "Kiru",
        "kumbotso",
        "Ghari",
        "Kura",
        "Madobi",
        "Makoda",
        "Minjibir",
        "Nasarawa",
        "Rano",
        "Rimin Gado",
        "Rogo",
        "Shanono",
        "Sumaila",
        "Takali",
        "Tarauni",
        "Tofa",
        "Tsanyawa",
        "Tudun Wada",
        "Ungogo",
        "Warawa",
        "Wudil"
    ],
    Katsina: [
        "Bakori",
        "Batagarawa",
        "Batsari",
        "Baure",
        "Bindawa",
        "Charanchi",
        "Dandume",
        "Danja",
        "Dan Musa",
        "Daura",
        "Dutsi",
        "Dutsin-Ma",
        "Faskari",
        "Funtua",
        "Ingawa",
        "Jibia",
        "Kafur",
        "Kaita",
        "Kankara",
        "Kankia",
        "Katsina",
        "Kurfi",
        "Kusada",
        "Mai'Adua",
        "Malumfashi",
        "Mani",
        "Mashi",
        "Matazuu",
        "Musawa",
        "Rimi",
        "Sabuwa",
        "Safana",
        "Sandamu",
        "Zango"
    ],
    Kebbi: [
        "Aleiro",
        "Arewa-Dandi",
        "Argungu",
        "Augie",
        "Bagudo",
        "Birnin Kebbi",
        "Bunza",
        "Dandi",
        "Fakai",
        "Gwandu",
        "Jega",
        "Kalgo",
        "Koko/Besse",
        "Maiyama",
        "Ngaski",
        "Sakaba",
        "Shanga",
        "Suru",
        "Wasagu/Danko",
        "Yauri",
        "Zuru"
    ],
    Kogi: [
        "Adavi",
        "Ajaokuta",
        "Ankpa",
        "Bassa",
        "Dekina",
        "Ibaji",
        "Idah",
        "Igalamela-Odolu",
        "Ijumu",
        "Kabba/Bunu",
        "Kogi",
        "Lokoja",
        "Mopa-Muro",
        "Ofu",
        "Ogori/Mangongo",
        "Okehi",
        "Okene",
        "Olamabolo",
        "Omala",
        "Yagba East",
        "Yagba West"
    ],
    Kwara: [
        "Asa",
        "Baruten",
        "Edu",
        "Ekiti",
        "Ifelodun",
        "Ilorin East",
        "Ilorin West",
        "Irepodun",
        "Isin",
        "Kaiama",
        "Moro",
        "Offa",
        "Oke-Ero",
        "Oyun",
        "Pategi"
    ],
    Lagos: [
        "Agege",
        "Ajeromi-Ifelodun",
        "Alimosho",
        "Amuwo-Odofin",
        "Apapa",
        "Badagry",
        "Epe",
        "Eti-Osa",
        "Ibeju/Lekki",
        "Ifako-Ijaye",
        "Ikeja",
        "Ikorodu",
        "Kosofe",
        "Lagos Island",
        "Lagos Mainland",
        "Mushin",
        "Ojo",
        "Oshodi-Isolo",
        "Shomolu",
        "Surulere"
    ],
    Nasarawa: [
        "Akwanga",
        "Awe",
        "Doma",
        "Karu",
        "Keana",
        "Keffi",
        "Kokona",
        "Lafia",
        "Nasarawa",
        "Nasarawa-Eggon",
        "Obi",
        "Toto",
        "Wamba"
    ],
    Niger: [
        "Agaie",
        "Agwara",
        "Bida",
        "Borgu",
        "Bosso",
        "Chanchaga",
        "Edati",
        "Gbako",
        "Gurara",
        "Katcha",
        "Kontagora",
        "Lapai",
        "Lavun",
        "Magama",
        "Mariga",
        "Mashegu",
        "Mokwa",
        "Muya",
        "Pailoro",
        "Rafi",
        "Rijau",
        "Shiroro",
        "Suleja",
        "Tafa",
        "Wushishi"
    ],
    Ogun: [
        "Abeokuta North",
        "Abeokuta South",
        "Ado-Odo/Ota",
        "Yewa North",
        "Yewa South",
        "Ewekoro",
        "Ifo",
        "Ijebu East",
        "Ijebu North",
        "Ijebu North East",
        "Ijebu Ode",
        "Ikenne",
        "Imeko-Afon",
        "Ipokia",
        "Obafemi-Owode",
        "Ogun Waterside",
        "Odeda",
        "Odogbolu",
        "Remo North",
        "Shagamu"
    ],
    Ondo: [
        "Akoko North East",
        "Akoko North West",
        "Akoko South Akure East",
        "Akoko South West",
        "Akure North",
        "Akure South",
        "Ese-Odo",
        "Idanre",
        "Ifedore",
        "Ilaje",
        "Ile-Oluji",
        "Okeigbo",
        "Irele",
        "Odigbo",
        "Okitipupa",
        "Ondo East",
        "Ondo West",
        "Ose",
        "Owo"
    ],
    Osun: [
        "Aiyedade",
        "Aiyedire",
        "Atakumosa East",
        "Atakumosa West",
        "Boluwaduro",
        "Boripe",
        "Ede North",
        "Ede South",
        "Egbedore",
        "Ejigbo",
        "Ife Central",
        "Ife East",
        "Ife North",
        "Ife South",
        "Ifedayo",
        "Ifelodun",
        "Ila",
        "Ilesha East",
        "Ilesha West",
        "Irepodun",
        "Irewole",
        "Isokan",
        "Iwo",
        "Obokun",
        "Odo-Otin",
        "Ola-Oluwa",
        "Olorunda",
        "Oriade",
        "Orolu",
        "Osogbo"
    ],
    Oyo: [
        "Afijio",
        "Akinyele",
        "Atiba",
        "Atisbo",
        "Egbeda",
        "Ibadan Central",
        "Ibadan North",
        "Ibadan North West",
        "Ibadan South East",
        "Ibadan South West",
        "Ibarapa Central",
        "Ibarapa East",
        "Ibarapa North",
        "Ido",
        "Irepo",
        "Iseyin",
        "Itesiwaju",
        "Iwajowa",
        "Kajola",
        "Lagelu Ogbomosho North",
        "Ogbomosho South",
        "Ogo Oluwa",
        "Olorunsogo",
        "Oluyole",
        "Ona-Ara",
        "Orelope",
        "Ori Ire",
        "Oyo East",
        "Oyo West",
        "Saki East",
        "Saki West",
        "Surulere"
    ],
    Plateau: [
        "Barikin Ladi",
        "Bassa",
        "Bokkos",
        "Jos East",
        "Jos North",
        "Jos South",
        "Kanam",
        "Kanke",
        "Langtang North",
        "Langtang South",
        "Mangu",
        "Mikang",
        "Pankshin",
        "Qua'an Pan",
        "Riyom",
        "Shendam",
        "Wase"
    ],
    Rivers: [
        "Abua/Odual",
        "Ahoada East",
        "Ahoada West",
        "Akuku Toru",
        "Andoni",
        "Asari-Toru",
        "Bonny",
        "Degema",
        "Emohua",
        "Eleme",
        "Etche",
        "Gokana",
        "Ikwerre",
        "Khana",
        "Obio/Akpor",
        "Ogba/Egbema/Ndoni",
        "Ogu/Bolo",
        "Okrika",
        "Omumma",
        "Opobo/Nkoro",
        "Oyigbo",
        "Port-Harcourt",
        "Tai"
    ],
    Sokoto: [
        "Binji",
        "Bodinga",
        "Dange-shnsi",
        "Gada",
        "Goronyo",
        "Gudu",
        "Gawabawa",
        "Illela",
        "Isa",
        "Kware",
        "kebbe",
        "Rabah",
        "Sabon birni",
        "Shagari",
        "Silame",
        "Sokoto North",
        "Sokoto South",
        "Tambuwal",
        "Tqngaza",
        "Tureta",
        "Wamako",
        "Wurno",
        "Yabo"
    ],
    Taraba: [
        "Ardo-kola",
        "Bali",
        "Donga",
        "Gashaka",
        "Cassol",
        "Ibi",
        "Jalingo",
        "Karin-Lamido",
        "Kurmi",
        "Lau",
        "Sardauna",
        "Takum",
        "Ussa",
        "Wukari",
        "Yorro",
        "Zing"
    ],
    Yobe: [
        "Bade",
        "Bursari",
        "Damaturu",
        "Fika",
        "Fune",
        "Geidam",
        "Gujba",
        "Gulani",
        "Jakusko",
        "Karasuwa",
        "Karawa",
        "Machina",
        "Nangere",
        "Nguru Potiskum",
        "Tarmua",
        "Yunusari",
        "Yusufari"
    ],
    Zamfara: [
        "Anka",
        "Bakura",
        "Birnin Magaji",
        "Bukkuyum",
        "Bungudu",
        "Gummi",
        "Gusau",
        "Kaura",
        "Namoda",
        "Maradun",
        "Maru",
        "Shinkafi",
        "Talata Mafara",
        "Tsafe",
        "Zurmi"
    ]
}
export const mockOrders = [
    {
        _id: "68cad4d2aafab723cf4e4235",
        orderRef: "ORD-MFO565GV-D9LY",
        clientId: "683c79a1eb06f7d0b17e9f0a",
        status: "confirmed",
        orderType: "instant",
        priority: "normal",
        package: {
            category: "mobilePhone",
            description: "iPhone 18 Max",
            isFragile: true,
            requiresSpecialHandling: true,
            images: [
                {
                    id: "1758123248529_2sdl7wszx",
                    url: "https://aanglogistics.s3.eu-north-1.amazonaws.com/Orders/683c79a1eb06f7d0b17e9f0a/68cad4d2aafab723cf4e4235/images/1758123245971-80f628e2-e167-4b54-bd98-d3ad10e151d2-image_1758123244423.png",
                    fileName: "image_1758123244423.png",
                    size: 118735
                }
            ],
            specialInstructions: "Handle with care"
        },
        location: {
            pickUp: {
                address: "Univ of Ibadan, Ibadan 200132, Oyo, Nigeria",
                landmark: "Senate Building",
                contactPerson: { name: "Kofo", phone: "07068518999" }
            },
            dropOff: {
                address: "Univ of Lagos, Lagos Mainland, Lagos 101245, Lagos, Nigeria",
                landmark: "Henry Carr Postgraduate Hostel",
                contactPerson: { name: "Mr Sanusi", phone: "07068518999" }
            }
        },
        pricing: { totalAmount: 84190, currency: "NGN" },
        payment: { method: "PayStack", status: "paid", paidAt: "2025-09-17T15:36:11.210Z" },
        deliveryToken: "6963F7",
        tokenVerified: { verified: false },
        insurance: { isInsured: true, declaredValue: 2500000 },
        createdAt: "2025-09-17T15:33:38.491Z",
        updatedAt: "2025-09-17T15:36:11.212Z"
    },
    {
        _id: "68cb5215b1790894b3254dd8",
        orderRef: "ORD-MFOO9GVE-FE3Z",
        clientId: "683c79a1eb06f7d0b17e9f0a",
        status: "pending",
        orderType: "instant",
        priority: "high",
        package: {
            category: "laptop",
            description: "Lenovo ThinkPad",
            isFragile: true,
            requiresSpecialHandling: true,
            images: [{
                id: "1758155327742_762vh6yir",
                url: "https://aanglogistics.s3.eu-north-1.amazonaws.com/Orders/683c79a1eb06f7d0b17e9f0a/68cb5215b1790894b3254dd8/images/1758155320543-58b741e9-d630-4b2c-b1d0-587ad3f05262-image_1758155319557.png"
            }],
            specialInstructions: "Handle with care"
        },
        location: {
            pickUp: {
                address: "Univ of Ibadan, Ibadan 200132, Oyo, Nigeria",
                landmark: "Senate Building",
                contactPerson: { name: "Kofo", phone: "07068518999" }
            },
            dropOff: {
                address: "Univ of Lagos, Lagos Mainland, Lagos 101245, Lagos, Nigeria",
                landmark: "Henry Carr Postgraduate Hostel",
                contactPerson: { name: "Mr Sanusi", phone: "07068518999" }
            }
        },
        pricing: { totalAmount: 84190, currency: "NGN" },
        payment: { method: "PayStack", status: "paid", paidAt: "2025-09-18T00:30:05.575Z" },
        deliveryToken: "5DDCCE",
        tokenVerified: { verified: false },
        insurance: { isInsured: true, declaredValue: 2500000 },
        createdAt: "2025-09-18T00:28:05.950Z",
        updatedAt: "2025-09-18T00:30:05.577Z"
    },
    {
        _id: "68cbc4df55e42ce746174bca",
        orderRef: "ORD-MFP5RB9X-RKOK",
        clientId: "683c79a1eb06f7d0b17e9f0a",
        status: "draft",
        orderType: "instant",
        priority: "normal",
        package: {
            category: "others",
            description: "Draft package",
            isFragile: false,
            requiresSpecialHandling: false,
            images: []
        },
        location: {
            pickUp: { address: "TBD", coordinates: { coordinates: [0, 0] } },
            dropOff: { address: "TBD", coordinates: { coordinates: [0, 0] } }
        },
        pricing: { totalAmount: 0, currency: "NGN" },
        payment: { method: "PayStack", status: "pending" },
        deliveryToken: "75F3D3",
        tokenVerified: { verified: false },
        metadata: { draftProgress: { step: 1 } },
        createdAt: "2025-09-18T08:37:51.967Z",
        updatedAt: "2025-09-18T08:37:51.967Z"
    },
    {
        _id: "68d12335e6fe2e33bbbb7d90",
        orderRef: "ORD-MK2Q8P1K-7YTR",
        clientId: "683c79a1eb06f7d0b17e9f0b",
        status: "assigned",
        orderType: "instant",
        priority: "urgent",
        package: {
            category: "parcel",
            description: "Important documents",
            isFragile: false,
            requiresSpecialHandling: false,
            images: []
        },
        location: {
            pickUp: {
                address: "Lekki Phase 1, Lagos",
                landmark: "Admiralty Way",
                contactPerson: { name: "James", phone: "08123456789" }
            },
            dropOff: {
                address: "Yaba, Lagos",
                landmark: "Yaba Tech",
                contactPerson: { name: "Sarah", phone: "09087654321" }
            }
        },
        pricing: { totalAmount: 3500, currency: "NGN" },
        payment: { method: "Wallet", status: "paid" },
        driverAssignment: {
            driverId: "68a12345e6fe2e33bbbb7d88",
            driverInfo: {
                name: "Michael Adebayo",
                phone: "08034567890",
                vehicleType: "motorcycle",
                vehicleNumber: "ABC-123-KJ",
                rating: 4.8
            },
            status: "assigned"
        },
        deliveryToken: "A1B2C3",
        tokenVerified: { verified: false },
        createdAt: "2025-09-22T10:10:09.201Z",
        updatedAt: "2025-09-23T12:00:00.000Z"
    },
    {
        _id: "68d12335e6fe2e33bbbb7d91",
        orderRef: "ORD-PL90ASQ1-9ZQW",
        clientId: "683c79a1eb06f7d0b17e9f0c",
        status: "in_transit",
        orderType: "scheduled",
        priority: "normal",
        package: {
            category: "fragile",
            description: "Glass artwork",
            isFragile: true,
            requiresSpecialHandling: true,
            images: []
        },
        location: {
            pickUp: {
                address: "Ikeja City Mall",
                landmark: "Main entrance",
                contactPerson: { name: "David", phone: "07012345678" }
            },
            dropOff: {
                address: "Unilag Akoka",
                landmark: "Gate entrance",
                contactPerson: { name: "Peace", phone: "08098765432" }
            }
        },
        pricing: { totalAmount: 5500, currency: "NGN" },
        payment: { method: "BankTransfer", status: "paid" },
        driverAssignment: {
            driverId: "68a12345e6fe2e33bbbb7d89",
            driverInfo: {
                name: "Fatima Bello",
                phone: "09023456789",
                vehicleType: "van",
                vehicleNumber: "DEF-456-GH",
                rating: 4.9
            },
            status: "accepted",
            currentLocation: { lat: 6.5244, lng: 3.3792 }
        },
        deliveryToken: "X9Y8Z7",
        tokenVerified: { verified: false },
        createdAt: "2025-09-23T07:30:00.000Z",
        updatedAt: "2025-09-23T13:10:00.000Z"
    },
    {
        _id: "68d12335e6fe2e33bbbb7d92",
        orderRef: "ORD-DELIVERED-001",
        clientId: "683c79a1eb06f7d0b17e9f0d",
        status: "delivered",
        orderType: "instant",
        priority: "low",
        package: {
            category: "food",
            description: "Birthday cake",
            isFragile: true,
            requiresSpecialHandling: false,
            images: []
        },
        location: {
            pickUp: {
                address: "Victoria Island bakery",
                landmark: "Tiamiyu Savage Street",
                contactPerson: { name: "Baker John", phone: "08145678912" }
            },
            dropOff: {
                address: "Surulere residence",
                landmark: "Adelabu Street",
                contactPerson: { name: "Mrs. Adekola", phone: "07056789123" }
            }
        },
        pricing: { totalAmount: 2700, currency: "NGN" },
        payment: { method: "PayStack", status: "paid" },
        driverAssignment: {
            driverId: "68a12345e6fe2e33bbbb7d90",
            driverInfo: {
                name: "Ahmed Ibrahim",
                phone: "08167890234",
                vehicleType: "motorcycle",
                vehicleNumber: "GHI-789-JK",
                rating: 4.7
            },
            status: "completed"
        },
        deliveryConfirmation: {
            verifiedAt: "2025-09-20T11:45:00.000Z",
            verifiedBy: { name: "Mrs. Adekola", phone: "07056789123" }
        },
        deliveryToken: "M5N4P3",
        tokenVerified: { verified: true, verifiedAt: "2025-09-20T11:45:00.000Z" },
        createdAt: "2025-09-20T09:00:00.000Z",
        updatedAt: "2025-09-20T11:45:00.000Z"
    }
];



// Validation

// Validation helper functions
export const isValidEmail = (email) => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
};

export const isValidPhone = (phone) => {
    // Nigerian phone format: +234..., 234..., 0...
    const phoneRegex = /^(?:\+?234|0)[789][01]\d{8}$/;
    return phoneRegex.test(phone.replace(/\s/g, ''));
};

export const isValidDate = (dateString) => {
    if (!dateString) return true; // Optional field
    const date = new Date(dateString);
    return date instanceof Date && !isNaN(date);
};

export const isFutureDate = (dateString) => {
    return new Date(dateString) > new Date();
};

export const isUnderage = (dateString) => {
    const birthDate = new Date(dateString);
    const today = new Date();
    const age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();

    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
        return age - 1 < 18;
    }
    return age < 18;
};